services:
  db:
    image: postgres:15-alpine
    container_name: lifepulse-db
    environment:
      POSTGRES_DB: lifepulse
      POSTGRES_USER: lifepulse
      POSTGRES_PASSWORD: lifepulse
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
